noop(sh) print warnings/errors to stderr

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -6,21 +6,21 @@ SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/../ && pwd )"
 
 if [[ "x$SASS_LIBSASS_PATH" == "x" ]]; then
   export SASS_LIBSASS_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/../../libsass/ && pwd )"
-  echo "SASS_LIBSASS_PATH variable is missing missing, so using $SASS_LIBSASS_PATH"
+  echo "SASS_LIBSASS_PATH variable is missing missing, so using $SASS_LIBSASS_PATH" >&2
 fi
 if [[ ! -d "$SASS_LIBSASS_PATH" ]]; then
   git clone https://github.com/sass/libsass.git "$SASS_LIBSASS_PATH"
 else
-    echo "LibSass already exists, skiping Git Clone"
+  echo "LibSass already exists, skiping Git Clone" >&2
 fi
 
 if [[ "x$SASS_SPEC_PATH" == "x" ]]; then
     export SASS_SPEC_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/../../sass-spec/ && pwd )"
-    echo "SASS_SPEC_PATH variable is missing, so using $SASS_SPEC_PATH"
+    echo "SASS_SPEC_PATH variable is missing, so using $SASS_SPEC_PATH" >&2
 fi
 
 if [[ ! -d "$SASS_SPEC_PATH" ]]; then
   git clone https://github.com/sass/sass-spec.git "$SASS_SPEC_PATH"
 else
-    echo "sass-spec already exists, skiping Git Clone"
+    echo "sass-spec already exists, skiping Git Clone" >&2
 fi
